import { useEffect, useRef, useState } from 'react'
import type { FormEvent, ReactNode } from 'react'
import { ApiError } from '../../api'
import { LoadingState } from '../../components/LoadingState'
import { changeServiceStatus, createService, getService, listServices, updateService } from './serviceApi'
import type { Service, ServiceInput, ServiceList } from './types'

type User = { roles: string[] }
type Props = { path: string; user: User; go: (path: string, replace?: boolean) => void; onSessionExpired: () => void }
type Errors = Record<string, string[]>
const blank: ServiceInput = { code: '', name: '', description: '', basePrice: '' }
const canMutate = (user: User) => user.roles.some(role => role === 'ADMIN' || role === 'MANAGER')

export function ServicesRoutes(props: Props) {
  if (props.path === '/servicos') return <ListPage {...props} />
  if (props.path === '/servicos/novo') return <FormPage {...props} />
  const edit = props.path.match(/^\/servicos\/([^/]+)\/editar$/); if (edit) return <FormPage {...props} serviceId={edit[1]} />
  const detail = props.path.match(/^\/servicos\/([^/]+)$/); if (detail) return <DetailPage {...props} serviceId={detail[1]} />
  return <section className="card"><h2>Página não encontrada</h2><p>O endereço de Serviços informado não existe.</p><button onClick={() => props.go('/servicos')}>Ir para Serviços</button></section>
}

function ListPage({ user, go, onSessionExpired }: Props) {
  const editable = canMutate(user); const [search, setSearch] = useState(''), [filter, setFilter] = useState('all'), [sort, setSort] = useState('code'), [direction, setDirection] = useState('asc'), [page, setPage] = useState(1), [data, setData] = useState<ServiceList | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState('')
  const load = async () => { setLoading(true); setError(''); try { const query = new URLSearchParams({ page: String(page), pageSize: '25', sort, direction }); if (search.trim()) query.set('search', search.trim()); if (editable && filter !== 'all') query.set('isActive', filter); setData(await listServices(query)) } catch (caught) { setError(message(caught, onSessionExpired, 'Não foi possível carregar os serviços.')) } finally { setLoading(false) } }
  useEffect(() => { const timer = setTimeout(() => { void load() }, 350); return () => clearTimeout(timer) }, [search, filter, sort, direction, page])
  const totalPages = data ? Math.max(1, Math.ceil(data.totalCount / data.pageSize)) : 1
  return <><div className="page-title"><div><p className="eyebrow">Cadastro</p><h2>Serviços</h2><p>Gerencie os serviços oferecidos pela empresa.</p></div>{editable && <button onClick={() => go('/servicos/novo')}>Novo serviço</button>}</div><section className="card"><div className="filters"><label>Buscar<input value={search} maxLength={200} placeholder="Código ou nome" onChange={event => { setSearch(event.target.value); setPage(1) }} /></label>{editable && <label>Status<select value={filter} onChange={event => { setFilter(event.target.value); setPage(1) }}><option value="all">Todos</option><option value="true">Ativos</option><option value="false">Inativos</option></select></label>}<label>Ordenar por<select value={sort} onChange={event => { setSort(event.target.value); setPage(1) }}><option value="code">Código</option><option value="name">Nome</option><option value="updatedAt">Última atualização</option><option value="createdAt">Cadastro</option></select></label><label>Direção<select value={direction} onChange={event => setDirection(event.target.value)}><option value="asc">Crescente</option><option value="desc">Decrescente</option></select></label><button className="secondary" disabled={loading} onClick={() => void load()}>Atualizar</button></div>{error && <ErrorPanel message={error} retry={load} />}{loading ? <LoadingState /> : data?.items.length === 0 ? <div className="empty-state"><h3>{search || filter !== 'all' ? 'Nenhum resultado encontrado' : 'Nenhum serviço cadastrado'}</h3><p>{search || filter !== 'all' ? 'Ajuste os filtros ou tente outra busca.' : 'Quando houver serviços cadastrados, eles aparecerão nesta lista.'}</p></div> : data && <><div className="table-wrap"><table><thead><tr><th>Código</th><th>Nome</th><th>Preço base</th><th>Status</th><th>Última atualização</th><th>Ações</th></tr></thead><tbody>{data.items.map(service => <tr key={service.id}><td>{service.code}</td><td>{service.name}</td><td>{price(service.basePrice)}</td><td><Status active={service.isActive} /></td><td>{date(service.updatedAtUtc)}</td><td className="actions"><button className="secondary" onClick={() => go(`/servicos/${service.id}`)}>Ver detalhes</button>{editable && <button className="secondary" onClick={() => go(`/servicos/${service.id}/editar`)}>Editar</button>}</td></tr>)}</tbody></table></div><div className="pagination"><span>Página {data.page} de {totalPages} · {data.totalCount} serviço(s)</span><button className="secondary" disabled={loading || page <= 1} onClick={() => setPage(page - 1)}>Anterior</button><button className="secondary" disabled={loading || page >= totalPages} onClick={() => setPage(page + 1)}>Próxima</button></div></>}</section></>
}

function FormPage({ user, go, onSessionExpired, serviceId }: Props & { serviceId?: string }) {
  const editing = Boolean(serviceId), [input, setInput] = useState<ServiceInput>(blank), [version, setVersion] = useState(''), [loading, setLoading] = useState(editing), [pending, setPending] = useState(false), [errors, setErrors] = useState<Errors>({}), [notice, setNotice] = useState(''), [conflict, setConflict] = useState(false), request = useRef(0)
  const load = async () => { if (!serviceId) return; const id = ++request.current; setLoading(true); try { const service = await getService(serviceId); if (id === request.current) { setInput({ code: service.code, name: service.name, description: service.description ?? '', basePrice: service.basePrice?.toFixed(2) ?? '' }); setVersion(service.version); setConflict(false) } } catch (caught) { if (id === request.current) setNotice(message(caught, onSessionExpired, 'Não foi possível carregar este serviço.')) } finally { if (id === request.current) setLoading(false) } }
  useEffect(() => { void load() }, [serviceId]); if (!canMutate(user)) return <Denied go={go} />; if (loading) return <LoadingState size="lg" />
  const submit = async (event: FormEvent) => { event.preventDefault(); const local = validate(input); setErrors(local); if (Object.keys(local).length || pending) return; setPending(true); setNotice(''); try { const service = editing ? await updateService(serviceId!, input, version) : await createService(input); go(`/servicos/${service.id}`, true) } catch (caught) { const api = caught instanceof ApiError ? caught : null; setErrors(api?.errors ?? {}); setConflict(api?.status === 409 && !api.errors.code); setNotice(message(caught, onSessionExpired, 'Não foi possível salvar o serviço.')) } finally { setPending(false) } }
  return <section className="card form-card"><p className="eyebrow">Serviços</p><h2>{editing ? 'Editar serviço' : 'Novo serviço'}</h2><p>Cadastre a definição reutilizável do serviço.</p>{conflict && <Conflict reload={load} />}{notice && <p className="error" role="alert">{notice}</p>}<form onSubmit={submit}><Fields input={input} setInput={setInput} errors={errors} disabled={pending} /><div className="actions"><button disabled={pending}>{pending ? 'Salvando...' : 'Salvar serviço'}</button><button type="button" className="secondary" disabled={pending} onClick={() => go(editing ? `/servicos/${serviceId}` : '/servicos')}>Cancelar</button></div></form></section>
}

function DetailPage({ user, go, onSessionExpired, serviceId }: Props & { serviceId: string }) {
  const editable = canMutate(user), [service, setService] = useState<Service | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState(''), [confirm, setConfirm] = useState(false), [pending, setPending] = useState(false)
  const load = async () => { setLoading(true); setError(''); try { setService(await getService(serviceId)) } catch (caught) { setError(message(caught, onSessionExpired, 'Não foi possível carregar este serviço.')) } finally { setLoading(false) } }; useEffect(() => { void load() }, [serviceId]);
  const changeStatus = async () => { if (!service || pending) return; setPending(true); try { setService(await changeServiceStatus(service.id, !service.isActive, service.version)); setConfirm(false) } catch (caught) { setError(message(caught, onSessionExpired, 'Não foi possível alterar o status do serviço.')) } finally { setPending(false) } }
  if (loading) return <LoadingState size="lg" />; if (!service) return <section className="card">{error ? <ErrorPanel message={error} retry={load} /> : null}<button onClick={() => go('/servicos')}>Voltar para Serviços</button></section>
  return <><div className="page-title"><div><p className="eyebrow">Serviços</p><h2>{service.name}</h2><p>Código: {service.code}</p></div><div className="actions">{editable && <button className="secondary" onClick={() => go(`/servicos/${service.id}/editar`)}>Editar</button>}{editable && <button onClick={() => setConfirm(true)}>{service.isActive ? 'Desativar' : 'Ativar'}</button>}</div></div><section className="card service-detail-card"><dl className="service-detail-grid"><div className="service-detail-item"><dt>Código</dt><dd>{service.code}</dd></div><div className="service-detail-item"><dt>Status</dt><dd><Status active={service.isActive} /></dd></div><div className="service-detail-item service-description"><dt>Descrição</dt><dd>{service.description || '—'}</dd></div><div className="service-detail-item"><dt>Preço base</dt><dd>{price(service.basePrice)}</dd></div><div className="service-detail-item"><dt>Cadastrado em</dt><dd>{date(service.createdAtUtc)}</dd></div><div className="service-detail-item"><dt>Última atualização</dt><dd>{date(service.updatedAtUtc)}</dd></div></dl>{error && <ErrorPanel message={error} retry={load} />}</section>{confirm && <Confirm title={service.isActive ? 'Desativar serviço' : 'Ativar serviço'} pending={pending} cancel={() => setConfirm(false)} confirm={changeStatus}><p>Deseja {service.isActive ? 'desativar' : 'ativar'} o serviço {service.name}?</p></Confirm>}</>
}

function Fields({ input, setInput, errors, disabled }: { input: ServiceInput; setInput: (value: ServiceInput) => void; errors: Errors; disabled: boolean }) { const set = (key: keyof ServiceInput, value: string) => setInput({ ...input, [key]: value }); return <><Field label="Código *" error={errors.code}><input value={input.code} maxLength={50} required disabled={disabled} onChange={e => set('code', e.target.value.toUpperCase())} /></Field><Field label="Nome *" error={errors.name}><input value={input.name} maxLength={160} required disabled={disabled} onChange={e => set('name', e.target.value)} /></Field><Field label="Descrição" error={errors.description}><textarea value={input.description} maxLength={2000} disabled={disabled} onChange={e => set('description', e.target.value)} /></Field><Field label="Preço base (R$)" error={errors.basePrice}><input value={input.basePrice} inputMode="decimal" disabled={disabled} onChange={e => set('basePrice', e.target.value)} /></Field></> }
function Field({ label, error, children }: { label: string; error?: string[]; children: ReactNode }) { return <label>{label}{children}{error && <small className="error" role="alert">{error[0]}</small>}</label> }
function Status({ active }: { active: boolean }) { return <span className={`status ${active ? 'active' : 'inactive'}`}>{active ? 'Ativo' : 'Inativo'}</span> }
function ErrorPanel({ message, retry }: { message: string; retry: () => void }) { return <div className="error-panel" role="alert"><p>{message}</p><button className="secondary" onClick={() => void retry()}>Tentar novamente</button></div> }
function Conflict({ reload }: { reload: () => void }) { return <div className="error-panel" role="alert"><p>Este serviço foi alterado por outro usuário. Atualize os dados antes de tentar novamente.</p><button className="secondary" onClick={() => void reload()}>Atualizar dados</button></div> }
function Confirm({ title, children, pending, cancel, confirm }: { title: string; children: ReactNode; pending: boolean; cancel: () => void; confirm: () => void }) { return <div className="modal-backdrop"><section className="card modal" role="dialog" aria-modal="true" aria-label={title}><h2>{title}</h2>{children}<div className="actions"><button className="secondary" disabled={pending} onClick={cancel}>Cancelar</button><button disabled={pending} onClick={() => void confirm()}>{pending ? 'Processando...' : title}</button></div></section></div> }
function Denied({ go }: { go: Props['go'] }) { return <section className="card"><h2>Acesso negado</h2><p>Seu perfil permite somente a consulta de serviços ativos.</p><button onClick={() => go('/servicos')}>Voltar</button></section> }
function message(error: unknown, expired: () => void, fallback: string) { if (error instanceof ApiError) { if (error.status === 401) { expired(); return 'Sua sessão expirou. Entre novamente.' } if (error.status === 403) return 'Você não tem permissão para esta ação.'; if (error.status === 404) return 'O item solicitado não foi encontrado ou não está disponível.'; if (error.status >= 500) return 'O serviço está indisponível no momento. Tente novamente.'; if (error.message) return error.message } return fallback }
function validate(input: ServiceInput): Errors { const errors: Errors = {}; const code = input.code.trim(); const priceValue = input.basePrice.trim().replace(',', '.'); if (!/^[A-Z0-9][A-Z0-9._/-]*$/.test(code) || code.length < 2 || code.length > 50) errors.code = ['Informe um código válido entre 2 e 50 caracteres.']; if (input.name.trim().length < 2) errors.name = ['Informe o nome com pelo menos 2 caracteres.']; if (input.description.length > 2000) errors.description = ['A descrição deve ter no máximo 2.000 caracteres.']; if (priceValue && (!/^\d+(\.\d{1,2})?$/.test(priceValue) || Number(priceValue) < 0)) errors.basePrice = ['Informe um preço base não negativo com no máximo duas casas decimais.']; return errors }
function price(value: number | null) { return value === null ? '—' : new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(value) }
function date(value: string) { return new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)) }
