using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Tsdt.Api.Identity.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260925223947_AddQuotes")]
public partial class AddQuotes : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(name:"QuoteNumberCounters",columns:table=>new{Year=table.Column<int>(type:"integer",nullable:false),LastNumber=table.Column<int>(type:"integer",nullable:false)},constraints:table=>{table.PrimaryKey("PK_QuoteNumberCounters",x=>x.Year);table.CheckConstraint("CK_QuoteNumberCounters_LastNumber_Range","\"LastNumber\" >= 1 AND \"LastNumber\" <= 999999");});
        migrationBuilder.CreateTable(name:"Quotes",columns:table=>new{Id=table.Column<Guid>(type:"uuid",nullable:false),Number=table.Column<string>(type:"character varying(16)",maxLength:16,nullable:false),CustomerId=table.Column<Guid>(type:"uuid",nullable:false),CustomerLegalNameSnapshot=table.Column<string>(type:"character varying(200)",maxLength:200,nullable:false),CustomerCnpjSnapshot=table.Column<string>(type:"character varying(14)",maxLength:14,nullable:false),Status=table.Column<int>(type:"integer",nullable:false),TotalAmount=table.Column<decimal>(type:"numeric(18,2)",precision:18,scale:2,nullable:true),PaymentType=table.Column<int>(type:"integer",nullable:true),InstallmentCount=table.Column<int>(type:"integer",nullable:true),Notes=table.Column<string>(type:"character varying(2000)",maxLength:2000,nullable:true),CreatedAtUtc=table.Column<DateTimeOffset>(type:"timestamp with time zone",nullable:false),UpdatedAtUtc=table.Column<DateTimeOffset>(type:"timestamp with time zone",nullable:false),CreatedByUserId=table.Column<string>(type:"text",nullable:false),UpdatedByUserId=table.Column<string>(type:"text",nullable:false),Version=table.Column<Guid>(type:"uuid",nullable:false)},constraints:table=>{table.PrimaryKey("PK_Quotes",x=>x.Id);table.CheckConstraint("CK_Quotes_TotalAmount_NonNegative","\"TotalAmount\" IS NULL OR \"TotalAmount\" >= 0");table.ForeignKey("FK_Quotes_Customers_CustomerId",x=>x.CustomerId,"Customers","Id",onDelete:ReferentialAction.Restrict);});
        migrationBuilder.CreateTable(name:"QuoteAuditRecords",columns:table=>new{Id=table.Column<Guid>(type:"uuid",nullable:false),QuoteId=table.Column<Guid>(type:"uuid",nullable:false),ActorUserId=table.Column<string>(type:"text",nullable:false),Action=table.Column<string>(type:"character varying(80)",maxLength:80,nullable:false),OccurredAtUtc=table.Column<DateTimeOffset>(type:"timestamp with time zone",nullable:false),ChangedFields=table.Column<string>(type:"character varying(500)",maxLength:500,nullable:true)},constraints:table=>{table.PrimaryKey("PK_QuoteAuditRecords",x=>x.Id);table.ForeignKey("FK_QuoteAuditRecords_Quotes_QuoteId",x=>x.QuoteId,"Quotes","Id",onDelete:ReferentialAction.Restrict);});
        migrationBuilder.CreateTable(name:"QuoteItems",columns:table=>new{Id=table.Column<Guid>(type:"uuid",nullable:false),QuoteId=table.Column<Guid>(type:"uuid",nullable:false),ServiceId=table.Column<Guid>(type:"uuid",nullable:false),ServiceCodeSnapshot=table.Column<string>(type:"character varying(50)",maxLength:50,nullable:false),ServiceNameSnapshot=table.Column<string>(type:"character varying(160)",maxLength:160,nullable:false),DisplayOrder=table.Column<int>(type:"integer",nullable:false)},constraints:table=>{table.PrimaryKey("PK_QuoteItems",x=>x.Id);table.ForeignKey("FK_QuoteItems_Quotes_QuoteId",x=>x.QuoteId,"Quotes","Id",onDelete:ReferentialAction.Restrict);table.ForeignKey("FK_QuoteItems_Services_ServiceId",x=>x.ServiceId,"Services","Id",onDelete:ReferentialAction.Restrict);});
        migrationBuilder.CreateIndex(name:"IX_QuoteAuditRecords_QuoteId_OccurredAtUtc",table:"QuoteAuditRecords",columns:new[]{"QuoteId","OccurredAtUtc"});migrationBuilder.CreateIndex(name:"IX_QuoteItems_QuoteId_DisplayOrder",table:"QuoteItems",columns:new[]{"QuoteId","DisplayOrder"},unique:true);migrationBuilder.CreateIndex(name:"IX_QuoteItems_ServiceId",table:"QuoteItems",column:"ServiceId");migrationBuilder.CreateIndex(name:"IX_Quotes_CustomerId_CreatedAtUtc",table:"Quotes",columns:new[]{"CustomerId","CreatedAtUtc"});migrationBuilder.CreateIndex(name:"IX_Quotes_Number",table:"Quotes",column:"Number",unique:true);migrationBuilder.CreateIndex(name:"IX_Quotes_Status_UpdatedAtUtc",table:"Quotes",columns:new[]{"Status","UpdatedAtUtc"});
    }
    protected override void Down(MigrationBuilder migrationBuilder){migrationBuilder.DropTable(name:"QuoteAuditRecords");migrationBuilder.DropTable(name:"QuoteItems");migrationBuilder.DropTable(name:"QuoteNumberCounters");migrationBuilder.DropTable(name:"Quotes");}
}
