import { expect, test } from './customers-runtime.fixture'
import { api, cnpj, contactInput, createCustomer, createRoleSession, freshSeed, readyAdmin, unitInput } from './customers-hardening.helpers'

test('Customer and child text with HTML syntax stays inert in the UI', async ({ page }) => {
  const dialogs: string[] = []
  page.on('dialog', dialog => { dialogs.push(dialog.message()); void dialog.dismiss() })
  await readyAdmin(page)
  const payload = '<img data-e2e-xss src=x onerror="window.__e2eXss=1">'
  const customer = await createCustomer(page, freshSeed(), { legalName: `E2E ${payload}`, tradeName: `Trade ${payload}`, notes: `Notes ${payload}` })
  const contact = await api<{ version: string }>(page, 'POST', `/api/customers/${customer.id}/contacts`,
    { ...contactInput({ name: `Contact ${payload}` }), expectedVersion: customer.version })
  expect(contact.status).toBe(201)
  const unit = await api(page, 'POST', `/api/customers/${customer.id}/units`,
    { ...unitInput({ name: `Unit ${payload}` }), expectedVersion: contact.body.version })
  expect(unit.status).toBe(201)
  await page.goto(`/clientes/${customer.id}`)
  await expect(page.getByRole('heading', { name: `E2E ${payload}` })).toBeVisible()
  await expect(page.getByText(`Notes ${payload}`)).toBeVisible()
  await expect(page.getByText(`Contact ${payload}`).first()).toBeVisible()
  await expect(page.getByText(`Unit ${payload}`).first()).toBeVisible()
  expect(await page.evaluate(() => (window as Window & { __e2eXss?: number }).__e2eXss)).toBeUndefined()
  await expect(page.locator('[data-e2e-xss]')).toHaveCount(0)
  expect(dialogs).toEqual([])
})

test('Mobile Customers navigation, records, forms and dialogs remain usable at 400px', async ({ page }) => {
  await readyAdmin(page)
  const customer = await createCustomer(page, freshSeed())
  const contact = await api<{ version: string }>(page, 'POST', `/api/customers/${customer.id}/contacts`,
    { ...contactInput({ name: 'Contato móvel' }), expectedVersion: customer.version })
  expect(contact.status).toBe(201)
  expect((await api(page, 'POST', `/api/customers/${customer.id}/units`,
    { ...unitInput({ name: 'Unidade móvel' }), expectedVersion: contact.body.version })).status).toBe(201)
  await page.setViewportSize({ width: 400, height: 840 })
  await page.goto('/clientes')
  const menu = page.getByRole('button', { name: 'Menu' })
  await expect(menu).toBeVisible()
  await menu.click()
  await expect(page.getByRole('button', { name: 'Fechar menu' })).toHaveAttribute('aria-expanded', 'true')
  await page.getByRole('button', { name: 'Clientes' }).click()
  await expect(page.getByRole('heading', { name: 'Clientes' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Novo cliente' })).toBeVisible()
  await page.goto(`/clientes/${customer.id}`)
  await expect(page.locator('.mobile-record').filter({ hasText: 'Contato móvel' })).toBeVisible()
  await expect(page.locator('.mobile-record').filter({ hasText: 'Unidade móvel' })).toBeVisible()
  await page.getByRole('button', { name: 'Adicionar contato' }).click()
  await expect(page.getByRole('dialog', { name: 'Adicionar contato' })).toBeVisible()
  await expect(page.getByLabel('Nome', { exact: true })).toBeVisible()
  await page.getByRole('dialog').getByRole('button', { name: 'Cancelar' }).click()
  await page.getByRole('button', { name: 'Adicionar unidade' }).click()
  await expect(page.getByRole('dialog', { name: 'Adicionar unidade' })).toBeVisible()
  await expect(page.getByLabel('UF')).toBeVisible()
  expect(await page.getByLabel('UF').locator('option').evaluateAll(options => options.map(option => (option as HTMLOptionElement).value).filter(Boolean))).toEqual(
    ['AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO'])
  await page.getByRole('dialog').getByRole('button', { name: 'Cancelar' }).click()
  await page.getByRole('button', { name: 'Editar empresa' }).click()
  await expect(page.getByLabel('Razão social *')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)
})

test('List network failure and detail server error show recoverable Portuguese states', async ({ page }) => {
  await readyAdmin(page)
  const customer = await createCustomer(page, freshSeed())
  await page.route('**/api/customers?*', route => route.abort('failed'))
  await page.goto('/clientes')
  await expect(page.getByRole('alert')).toContainText(/não foi possível|indisponível/i)
  await page.unroute('**/api/customers?*')
  await page.getByRole('button', { name: 'Tentar novamente' }).click()
  await expect(page.getByRole('heading', { name: 'Clientes' })).toBeVisible()
  await page.route(`**/api/customers/${customer.id}`, route => route.fulfill({ status: 500, contentType: 'text/plain', body: 'RAW_SECRET_EXCEPTION' }))
  await page.goto(`/clientes/${customer.id}`)
  await expect(page.getByRole('heading', { name: 'Cliente indisponível' })).toBeVisible()
  await expect(page.getByRole('alert')).toContainText('O serviço está indisponível')
  await expect(page.getByText('RAW_SECRET_EXCEPTION')).toHaveCount(0)
  await page.unroute(`**/api/customers/${customer.id}`)
  await page.reload()
  await expect(page.getByRole('heading', { name: customer.legalName })).toBeVisible()
})

test('Customer create server failure preserves form values and hides raw response', async ({ page }) => {
  await readyAdmin(page)
  await page.goto('/clientes/novo')
  await page.getByLabel('Razão social *').fill('E2E Recovery Form')
  await page.getByLabel('CNPJ *').fill(cnpj(freshSeed()))
  await page.route('**/api/customers', route => {
    if (route.request().method() === 'POST') return route.fulfill({ status: 500, contentType: 'text/plain', body: 'RAW_SERVER_TRACE' })
    return route.continue()
  })
  await page.getByRole('button', { name: 'Criar cliente' }).click()
  await expect(page.getByRole('alert')).toContainText('O serviço está indisponível')
  await expect(page.getByLabel('Razão social *')).toHaveValue('E2E Recovery Form')
  await expect(page.getByText('RAW_SERVER_TRACE')).toHaveCount(0)
  await page.unroute('**/api/customers')
  await page.getByRole('button', { name: 'Criar cliente' }).click()
  await expect(page.getByRole('heading', { name: 'E2E Recovery Form' })).toBeVisible()
})

test('List 500, detail 404, update 500 and mutation 403 show recoverable states', async ({ page }) => {
  await readyAdmin(page)
  const customer = await createCustomer(page, freshSeed())
  await page.route('**/api/customers?*', route => route.fulfill({ status: 500, body: 'RAW_SERVER_TRACE' }))
  await page.goto('/clientes')
  await expect(page.getByRole('alert')).toContainText('O serviço está indisponível')
  await expect(page.getByText('RAW_SERVER_TRACE')).toHaveCount(0)
  await expect(page.getByText('Carregando clientes...')).toHaveCount(0)
  await page.unroute('**/api/customers?*')
  await page.getByRole('button', { name: 'Tentar novamente' }).click()
  await expect(page.getByRole('alert')).toHaveCount(0)

  await page.route(`**/api/customers/${customer.id}`, route => route.fulfill({ status: 404 }))
  await page.goto(`/clientes/${customer.id}`)
  await expect(page.getByRole('heading', { name: 'Cliente indisponível' })).toBeVisible()
  await expect(page.getByRole('alert')).toContainText('não foi encontrado')
  await expect(page.getByText('Carregando cliente...')).toHaveCount(0)
  await page.unroute(`**/api/customers/${customer.id}`)

  await page.goto(`/clientes/${customer.id}/editar`)
  await page.getByLabel('Nome fantasia').fill('E2E Unsaved Update')
  await page.route(`**/api/customers/${customer.id}`, route => route.request().method() === 'PUT'
    ? route.fulfill({ status: 500, body: 'RAW_SERVER_TRACE' }) : route.continue())
  await page.getByRole('button', { name: 'Salvar alterações' }).click()
  await expect(page.getByRole('alert')).toContainText('O serviço está indisponível')
  await expect(page.getByLabel('Nome fantasia')).toHaveValue('E2E Unsaved Update')
  await expect(page.getByText('RAW_SERVER_TRACE')).toHaveCount(0)
  await page.unroute(`**/api/customers/${customer.id}`)
  await page.getByRole('button', { name: 'Salvar alterações' }).click()
  await expect(page.getByRole('heading', { name: customer.legalName })).toBeVisible()

  await page.route(`**/api/customers/${customer.id}/deactivate`, route => route.fulfill({ status: 403, body: 'RAW_SERVER_TRACE' }))
  await page.getByRole('button', { name: 'Desativar cliente' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Desativar cliente' }).click()
  await expect(page.getByRole('alert')).toContainText('Você não tem permissão')
  await expect(page.getByText('RAW_SERVER_TRACE')).toHaveCount(0)
  await page.unroute(`**/api/customers/${customer.id}/deactivate`)
  await page.getByRole('dialog').getByRole('button', { name: 'Desativar cliente' }).click()
  await expect(page.getByRole('button', { name: 'Ativar cliente' })).toBeVisible()
})

test('Customer fields, modal focus and mobile menu expose usable keyboard names', async ({ page }) => {
  await readyAdmin(page)
  const customer = await createCustomer(page, freshSeed())
  await page.goto(`/clientes/${customer.id}/editar`)
  for (const label of ['Razão social *', 'Nome fantasia', 'CNPJ *', 'Observações']) {
    await expect(page.getByLabel(label)).toBeVisible()
  }
  await expect(page.getByRole('button', { name: 'Salvar alterações' })).toBeVisible()
  await page.goto(`/clientes/${customer.id}`)
  await page.getByRole('button', { name: 'Desativar cliente' }).click()
  await expect(page.getByRole('dialog', { name: 'Desativar cliente' })).toBeVisible()
  await expect(page.getByRole('dialog').getByRole('button', { name: 'Cancelar' })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: 'Adicionar contato' }).click()
  for (const label of ['Nome', 'Cargo ou departamento', 'E-mail', 'Telefone']) await expect(page.getByLabel(label, { exact: true })).toBeVisible()
  await page.getByRole('dialog').getByRole('button', { name: 'Cancelar' }).focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: 'Adicionar unidade' }).click()
  for (const label of ['Nome da unidade', 'Logradouro', 'Número', 'Cidade', 'CEP']) await expect(page.getByLabel(label, { exact: true })).toBeVisible()
  await expect(page.getByLabel('UF')).toBeVisible()
  await page.getByRole('dialog').getByRole('button', { name: 'Cancelar' }).focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.setViewportSize({ width: 400, height: 840 })
  const menu = page.getByRole('button', { name: 'Menu' })
  await menu.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('button', { name: 'Fechar menu' })).toHaveAttribute('aria-expanded', 'true')
  await page.keyboard.press('Enter')
  await expect(menu).toHaveAttribute('aria-expanded', 'false')
})

test('Deactivated session on Customers returns to login without showing protected data', async ({ newIsolatedPage }) => {
  const admin = await newIsolatedPage()
  const user = await newIsolatedPage()
  try {
    await readyAdmin(admin)
    const userId = await createRoleSession(admin, user, 'USER')
    await user.goto('/clientes')
    await expect(user.getByRole('heading', { name: 'Clientes' })).toBeVisible()
    expect((await api(admin, 'POST', `/api/admin/users/${userId}/deactivate`)).status).toBe(200)
    await user.getByLabel('Buscar').fill('session-invalidated')
    await expect(user.getByRole('heading', { name: 'Entrar' })).toBeVisible()
    await expect(user.getByRole('heading', { name: 'Clientes' })).toHaveCount(0)
    expect((await api(user, 'GET', '/api/customers')).status).toBe(401)
  } finally { await admin.close(); await user.close() }
})

test('Direct Customers routes, refresh and history recover from unknown paths', async ({ page }) => {
  await readyAdmin(page)
  const customer = await createCustomer(page, freshSeed())
  await page.goto('/clientes')
  await expect(page.getByRole('heading', { name: 'Clientes' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Clientes' })).toBeVisible()
  await page.goto('/clientes/novo')
  await expect(page.getByRole('heading', { name: 'Novo cliente' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Novo cliente' })).toBeVisible()
  await page.goto(`/clientes/${customer.id}`)
  await expect(page.getByRole('heading', { name: customer.legalName })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: customer.legalName })).toBeVisible()
  await page.goto(`/clientes/${customer.id}/editar`)
  await expect(page.getByRole('heading', { name: 'Editar cliente' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Editar cliente' })).toBeVisible()
  await page.goBack()
  await expect(page.getByRole('heading', { name: customer.legalName })).toBeVisible()
  await page.goForward()
  await expect(page.getByRole('heading', { name: 'Editar cliente' })).toBeVisible()
  await page.goto(`/clientes/${crypto.randomUUID()}`)
  await expect(page.getByRole('heading', { name: 'Cliente indisponível' })).toBeVisible()
  await page.goto('/clientes/not-a-guid')
  await expect(page.getByRole('heading', { name: /Página não encontrada|Cliente indisponível/ })).toBeVisible()
  await page.goto('/unknown-e2e-path')
  await expect(page.getByRole('heading', { name: 'Página não encontrada' })).toBeVisible()
})
