export type WorkOrderStatus = 'Draft' | 'Scheduled' | 'InProgress' | 'AwaitingClosure' | 'Closed' | 'Cancelled'
export type WorkOrderSource = 'Quote' | 'Contract'
export type WorkOrderItem = { id: string; serviceCodeSnapshot: string; serviceNameSnapshot: string; serviceLineCodeSnapshot: string; serviceLineNameSnapshot: string; displayOrder: number }
export type WorkOrderSummary = { id: string; number: string; sourceType: WorkOrderSource; quoteId: string; contractId: string | null; customerLegalNameSnapshot: string; status: WorkOrderStatus; assignedUserId: string | null; assignedUserNameSnapshot: string | null; scheduledStart: string | null; scheduledEnd: string | null; updatedAtUtc: string }
export type WorkOrder = WorkOrderSummary & { serviceAddressSnapshot: string; assignedUserEmailSnapshot: string | null; startedAtUtc: string | null; executionCompletedAtUtc: string | null; closedAtUtc: string | null; cancelledAtUtc: string | null; operationalNotes: string | null; completionNotes: string | null; createdAtUtc: string; version: string; items: WorkOrderItem[] }
export type WorkOrderList = { items: WorkOrderSummary[]; page: number; pageSize: number; totalCount: number }
export type WorkOrderHistory = { action: string; occurredAtUtc: string }
export type EligibleAssignee = { id: string; fullName: string; email: string; role: string }
export type Planning = { assignedUserId: string; scheduledStart: string; scheduledEnd: string; operationalNotes: string }
