using System.Data;
using System.Security.Claims;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using Tsdt.Api.Customers;
using Tsdt.Api.Identity;
using Tsdt.Api.Services;

namespace Tsdt.Api.Quotes;

public static class QuoteEndpoints
{
    private const string StaleMessage = "Este orçamento foi alterado por outro usuário. Atualize os dados e tente novamente.";
    private static readonly TimeZoneInfo SaoPaulo = TimeZoneInfo.FindSystemTimeZoneById("America/Sao_Paulo");
    public static void MapQuoteEndpoints(this WebApplication app)
    {
        var quotes = app.MapGroup("/api/quotes").RequireAuthorization(AuthorizationPolicies.CommercialAdmin);
        quotes.MapGet("", ListAsync); quotes.MapGet("/professionals", ProfessionalsAsync); quotes.MapGet("/summary", SummaryAsync); quotes.MapGet("/{id:guid}", GetAsync); quotes.MapGet("/{id:guid}/history", HistoryAsync); quotes.MapGet("/{id:guid}/approval-validation", GetApprovalValidationAsync); quotes.MapPost("", CreateAsync); quotes.MapPut("/{id:guid}", UpdateAsync);
        quotes.MapPost("/{id:guid}/visits", CreateVisitAsync); quotes.MapPost("/{id:guid}/visits/{visitId:guid}/reschedule", RescheduleVisitAsync); quotes.MapPost("/{id:guid}/visits/{visitId:guid}/complete", (Guid id, Guid visitId, HttpContext c, IAntiforgery a, ApplicationDbContext d) => ChangeVisitStatusAsync(id, visitId, QuoteVisitStatus.Completed, "VISIT_COMPLETED", c, a, d)); quotes.MapPost("/{id:guid}/visits/{visitId:guid}/cancel", (Guid id, Guid visitId, HttpContext c, IAntiforgery a, ApplicationDbContext d) => ChangeVisitStatusAsync(id, visitId, QuoteVisitStatus.Cancelled, "VISIT_CANCELLED", c, a, d));
        quotes.MapPost("/{id:guid}/submit", SendForApprovalAsync);
        quotes.MapPost("/{id:guid}/client-response", RegisterClientResponseAsync);
        quotes.MapPost("/{id:guid}/reopen", ReopenAsync);
        quotes.MapPost("/{id:guid}/cancel", CancelAsync);
        quotes.MapPost("/{id:guid}/approve", (Guid id, QuoteVersionRequest r, HttpContext c, IAntiforgery a, ApplicationDbContext d) => RegisterClientResponseAsync(id, new RegisterClientResponseRequest(r.ExpectedVersion, QuoteClientResponseType.Approved, null), c, a, d));
        quotes.MapPost("/{id:guid}/reject", (Guid id, QuoteVersionRequest r, HttpContext c, IAntiforgery a, ApplicationDbContext d) => RegisterClientResponseAsync(id, new RegisterClientResponseRequest(r.ExpectedVersion, QuoteClientResponseType.Rejected, null), c, a, d));
        quotes.MapPost("/{id:guid}/expire", (Guid id, QuoteVersionRequest r, HttpContext c, IAntiforgery a, ApplicationDbContext d) => TransitionAsync(id, r, [QuoteStatus.AwaitingApproval], QuoteStatus.Expired, "QUOTE_EXPIRED", c, a, d));
    }
    private static async Task<IResult> ProfessionalsAsync(ApplicationDbContext db) => Results.Ok(await (from user in EligibleProfessionalQuery.Apply(db) join membership in db.UserRoles on user.Id equals membership.UserId join role in db.Roles on membership.RoleId equals role.Id orderby user.FullName select new EligibleProfessionalResponse(user.Id, user.FullName, user.Email!, role.Name!)).ToListAsync());
    private static async Task<IResult> ListAsync(int? page, int? pageSize, string? search, QuoteStatus? status, QuoteListScope? scope, Guid? serviceId, string? responsibleUserId, DateTimeOffset? createdFrom, DateTimeOffset? createdTo, DateTimeOffset? sentFrom, DateTimeOffset? sentTo, bool? awaitingResponse, bool? expired, string? sort, string? direction, ApplicationDbContext db)
    {
        if (search?.Length > 200) return Results.ValidationProblem(new Dictionary<string,string[]> { ["search"] = ["A busca deve ter no máximo 200 caracteres."] });
        var p = Math.Max(page ?? 1, 1); var size = Math.Clamp(pageSize ?? 25, 1, 100); IQueryable<Quote> q = db.Quotes.AsNoTracking().Include(x=>x.ResponsibleUser).Include(x=>x.Visits).ThenInclude(x=>x.AssignedUser);
        var openStatuses = new[] { QuoteStatus.Draft, QuoteStatus.AwaitingApproval, QuoteStatus.ChangesRequested };
        if (status.HasValue) q = q.Where(x => x.Status == status);
        else if (scope is null or QuoteListScope.Open) q = q.Where(x => openStatuses.Contains(x.Status));
        else if (scope == QuoteListScope.Closed) q = q.Where(x => !openStatuses.Contains(x.Status));
        if (serviceId.HasValue) q = q.Where(x => x.Items.Any(item => item.ServiceId == serviceId)); if(!string.IsNullOrWhiteSpace(responsibleUserId))q=q.Where(x=>x.ResponsibleUserId==responsibleUserId); if (createdFrom.HasValue) q=q.Where(x=>x.CreatedAtUtc>=createdFrom); if(createdTo.HasValue)q=q.Where(x=>x.CreatedAtUtc<=createdTo); if(sentFrom.HasValue)q=q.Where(x=>x.SentForApprovalAt>=sentFrom); if(sentTo.HasValue)q=q.Where(x=>x.SentForApprovalAt<=sentTo); if(awaitingResponse==true)q=q.Where(x=>x.Status==QuoteStatus.AwaitingApproval); if(expired==true)q=q.Where(x=>x.Status==QuoteStatus.Expired || (x.Status==QuoteStatus.AwaitingApproval && x.ValidUntil!=null && x.ValidUntil<DateTimeOffset.UtcNow)); if (!string.IsNullOrWhiteSpace(search)) { var s = search.Trim().ToLowerInvariant(); var digits = new string(search.Where(char.IsDigit).ToArray()); q = q.Where(x => x.Number.ToLower().Contains(s) || x.CustomerLegalNameSnapshot.ToLower().Contains(s) || (digits.Length > 0 && x.CustomerCnpjSnapshot.Contains(digits))); }
        if (db.Database.ProviderName?.Contains("Sqlite", StringComparison.OrdinalIgnoreCase) == true)
        {
            var rows = await q.ToListAsync();
            var ordered = rows.OrderByDescending(x => x.UpdatedAtUtc).ThenByDescending(x => x.Number);
            return Results.Ok(new QuoteListResponse(ordered.Skip((p - 1) * size).Take(size).Select(ToSummary).ToList(), p, size, rows.Count));
        }
        var desc = string.Equals(direction, "desc", StringComparison.OrdinalIgnoreCase);
        q = (sort?.ToLowerInvariant(), desc) switch { ("customer", false) => q.OrderBy(x=>x.CustomerLegalNameSnapshot).ThenByDescending(x=>x.Number), ("customer", true) => q.OrderByDescending(x=>x.CustomerLegalNameSnapshot).ThenByDescending(x=>x.Number), ("createdat", false)=>q.OrderBy(x=>x.CreatedAtUtc).ThenByDescending(x=>x.Number), ("createdat",true)=>q.OrderByDescending(x=>x.CreatedAtUtc).ThenByDescending(x=>x.Number), ("updatedat",false)=>q.OrderBy(x=>x.UpdatedAtUtc).ThenByDescending(x=>x.Number), ("updatedat",true)=>q.OrderByDescending(x=>x.UpdatedAtUtc).ThenByDescending(x=>x.Number), ("number",false)=>q.OrderBy(x=>x.Number), ("number",true)=>q.OrderByDescending(x=>x.Number), _=>q.OrderByDescending(x=>x.UpdatedAtUtc).ThenByDescending(x=>x.Number) };
        var total = await q.CountAsync(); var offset = ((long)p-1)*size; if (offset > int.MaxValue) return Results.Ok(new QuoteListResponse([],p,size,total));
        var selected=await q.Skip((int)offset).Take(size).ToListAsync(); return Results.Ok(new QuoteListResponse(selected.Select(ToSummary).ToList(),p,size,total));
    }
    private static async Task<IResult> SummaryAsync(ApplicationDbContext db) { var counts=await db.Quotes.AsNoTracking().GroupBy(x=>x.Status).Select(x=>new { Status=x.Key, Count=x.Count() }).ToListAsync(); return Results.Ok(new QuoteCommercialSummaryResponse(counts.SingleOrDefault(x=>x.Status==QuoteStatus.Draft)?.Count??0,counts.SingleOrDefault(x=>x.Status==QuoteStatus.AwaitingApproval)?.Count??0,counts.SingleOrDefault(x=>x.Status==QuoteStatus.ChangesRequested)?.Count??0,counts.SingleOrDefault(x=>x.Status==QuoteStatus.Approved)?.Count??0)); }
    private static async Task<IResult> GetAsync(Guid id, ApplicationDbContext db) { var quote = await db.Quotes.AsNoTracking().Include(x=>x.Items).Include(x=>x.ResponsibleUser).Include(x=>x.Visits).ThenInclude(x=>x.AssignedUser).SingleOrDefaultAsync(x=>x.Id==id); return quote is null ? Results.NotFound() : Results.Ok(ToDetail(quote)); }
    private static async Task<IResult> GetApprovalValidationAsync(Guid id, ApplicationDbContext db)
    {
        var quote = await db.Quotes.AsNoTracking().Include(x => x.Items).SingleOrDefaultAsync(x => x.Id == id);
        if (quote is null) return Results.NotFound();
        return Results.Ok(new QuoteApprovalValidationResponse(await ApprovalErrorsAsync(quote, db)));
    }
    private static async Task<IResult> HistoryAsync(Guid id, ApplicationDbContext db) => !await db.Quotes.AnyAsync(x=>x.Id==id) ? Results.NotFound() : Results.Ok(await db.QuoteAuditRecords.AsNoTracking().Where(x=>x.QuoteId==id).OrderByDescending(x=>x.OccurredAtUtc).Select(x=>new QuoteHistoryResponse(x.Id,x.OccurredAtUtc,x.Action,x.ActorUserId,x.ChangedFields)).ToListAsync());
    private static async Task<IResult> CreateAsync(CreateQuoteRequest request, HttpContext context, IAntiforgery antiforgery, ApplicationDbContext db)
    {
        if (!await Csrf(context, antiforgery)) return CsrfFailure(); var input = Validate(request.CustomerId, request.Items, request.TotalAmount, request.PaymentType, request.InstallmentCount, request.Notes, request.EmployeeCount, request.RiskDegree); if (input.Errors is not null) return Results.ValidationProblem(input.Errors);
        var customer = await db.Customers.SingleOrDefaultAsync(x=>x.Id==request.CustomerId && x.IsActive); if (customer is null) return Results.ValidationProblem(new Dictionary<string,string[]> { ["customerId"]=["Selecione um cliente ativo."] });
        var services = await ActiveServicesAsync(db, input.Items!); if (services is null) return Results.ValidationProblem(new Dictionary<string,string[]> { ["items"]=["Selecione apenas serviços ativos."] });
        var serviceAddress = await ServiceAddressAsync(db, customer.Id, request.ServiceUnitId); if (request.ServiceUnitId.HasValue && serviceAddress is null) return Results.ValidationProblem(new Dictionary<string,string[]> { ["serviceUnitId"]=["Selecione uma unidade ativa do cliente."] });
        var actor = Actor(context); var responsible = string.IsNullOrWhiteSpace(request.ResponsibleUserId) ? null : request.ResponsibleUserId; if(responsible is not null && !await EligibleProfessionalQuery.ContainsAsync(db,responsible)) return Results.ValidationProblem(new Dictionary<string,string[]> { ["responsibleUserId"]=["Selecione um profissional responsÃ¡vel elegÃ­vel."] }); var now=DateTimeOffset.UtcNow; await using var tx=await db.Database.BeginTransactionAsync();
        var number = await AllocateNumberAsync(db, TimeZoneInfo.ConvertTime(now,SaoPaulo).Year); if (number is null) return Results.Conflict(new { error="A numeração anual de orçamentos atingiu o limite." });
        var quote=new Quote { Id=Guid.NewGuid(), Number=number, CustomerId=customer.Id, CustomerLegalNameSnapshot=customer.LegalName, CustomerCnpjSnapshot=customer.Cnpj, TotalAmount=input.TotalAmount, PaymentType=input.PaymentType, InstallmentCount=input.InstallmentCount, EmployeeCount=request.EmployeeCount, RiskDegree=request.RiskDegree, ServiceUnitId=request.ServiceUnitId, ServiceAddressSnapshot=serviceAddress, Notes=input.Notes, ResponsibleUserId=responsible, CreatedAtUtc=now, UpdatedAtUtc=now, CreatedByUserId=actor, UpdatedByUserId=actor, Version=Guid.NewGuid() };
        quote.Items=services.Select((s,i)=>new QuoteItem { Id=Guid.NewGuid(), QuoteId=quote.Id, ServiceId=s.Id, ServiceCodeSnapshot=s.Code, ServiceNameSnapshot=s.Name, DisplayOrder=i+1 }).ToList(); db.Quotes.Add(quote); Audit(db,quote,actor,"QUOTE_CREATED",null); await db.SaveChangesAsync(); await tx.CommitAsync(); quote.ResponsibleUser=responsible is null ? null : await db.Users.FindAsync(responsible); return Results.Created($"/api/quotes/{quote.Id}",ToDetail(quote));
    }
    private static async Task<IResult> UpdateAsync(Guid id, UpdateQuoteRequest request, HttpContext context, IAntiforgery antiforgery, ApplicationDbContext db)
    {
        if(!await Csrf(context,antiforgery)) return CsrfFailure(); var input=Validate(request.CustomerId,request.Items,request.TotalAmount,request.PaymentType,request.InstallmentCount,request.Notes,request.EmployeeCount,request.RiskDegree); if(input.Errors is not null)return Results.ValidationProblem(input.Errors);
        var quote=await db.Quotes.Include(x=>x.Items).SingleOrDefaultAsync(x=>x.Id==id); if(quote is null)return Results.NotFound(); if(quote.Version!=request.ExpectedVersion)return Stale(); if(quote.Status!=QuoteStatus.Draft)return StateConflict();
        var customerChanged=quote.CustomerId!=request.CustomerId; Customer? customer=null; if(customerChanged){customer=await db.Customers.SingleOrDefaultAsync(x=>x.Id==request.CustomerId&&x.IsActive);if(customer is null)return Results.ValidationProblem(new Dictionary<string,string[]> { ["customerId"]=["Selecione um cliente ativo."] });}
        var effectiveCustomerId=customerChanged?customer!.Id:quote.CustomerId; var serviceAddress=await ServiceAddressAsync(db,effectiveCustomerId,request.ServiceUnitId); if(request.ServiceUnitId.HasValue&&serviceAddress is null)return Results.ValidationProblem(new Dictionary<string,string[]> { ["serviceUnitId"]=["Selecione uma unidade ativa do cliente."] });
        var requested=input.Items!; var existing=quote.Items.ToDictionary(x=>x.Id); if(requested.Any(x=>x.Id.HasValue&&!existing.ContainsKey(x.Id.Value))) return Results.ValidationProblem(new Dictionary<string,string[]> { ["items"]=["Um item informado não pertence a este orçamento."] });
        var additions=requested.Where(x=>!x.Id.HasValue || existing[x.Id!.Value].ServiceId!=x.ServiceId).ToList(); var active=await ActiveServicesAsync(db, additions); if(active is null)return Results.ValidationProblem(new Dictionary<string,string[]> { ["items"]=["Selecione apenas serviços ativos."] });
        if (!string.IsNullOrWhiteSpace(request.ResponsibleUserId) && !await EligibleProfessionalQuery.ContainsAsync(db, request.ResponsibleUserId)) return Results.ValidationProblem(new Dictionary<string,string[]> { ["responsibleUserId"]=["Selecione um profissional responsÃ¡vel elegÃ­vel."] });
        var fields=new List<string>(); if(customerChanged){quote.CustomerId=customer!.Id;quote.CustomerLegalNameSnapshot=customer.LegalName;quote.CustomerCnpjSnapshot=customer.Cnpj;fields.Add("Customer");} if(quote.TotalAmount!=input.TotalAmount){quote.TotalAmount=input.TotalAmount;fields.Add("TotalAmount");} if(quote.PaymentType!=input.PaymentType){quote.PaymentType=input.PaymentType;fields.Add("PaymentType");} if(quote.InstallmentCount!=input.InstallmentCount){quote.InstallmentCount=input.InstallmentCount;fields.Add("InstallmentCount");} if(quote.EmployeeCount!=request.EmployeeCount){quote.EmployeeCount=request.EmployeeCount;fields.Add("EmployeeCount");} if(quote.RiskDegree!=request.RiskDegree){quote.RiskDegree=request.RiskDegree;fields.Add("RiskDegree");} if(quote.ServiceUnitId!=request.ServiceUnitId||quote.ServiceAddressSnapshot!=serviceAddress){quote.ServiceUnitId=request.ServiceUnitId;quote.ServiceAddressSnapshot=serviceAddress;fields.Add("ServiceAddress");} if(quote.Notes!=input.Notes){quote.Notes=input.Notes;fields.Add("Notes");} if(!string.IsNullOrWhiteSpace(request.ResponsibleUserId)&&quote.ResponsibleUserId!=request.ResponsibleUserId){quote.ResponsibleUserId=request.ResponsibleUserId;fields.Add("ResponsibleProfessional");}
        var next=new List<QuoteItem>(); foreach(var pair in requested.Select((x,i)=>(x,i))){if(pair.x.Id.HasValue&&existing.TryGetValue(pair.x.Id.Value,out var old)&&old.ServiceId==pair.x.ServiceId){old.DisplayOrder=pair.i+1;next.Add(old);}else{var service=active!.Single(x=>x.Id==pair.x.ServiceId);next.Add(new QuoteItem{Id=Guid.NewGuid(),QuoteId=quote.Id,ServiceId=service.Id,ServiceCodeSnapshot=service.Code,ServiceNameSnapshot=service.Name,DisplayOrder=pair.i+1});}}
        if(!quote.Items.Select(x=>x.Id).SequenceEqual(next.Select(x=>x.Id))){fields.Add("Items"); var retained=next.Select(x=>x.Id).ToHashSet(); db.QuoteItems.RemoveRange(quote.Items.Where(x=>!retained.Contains(x.Id))); quote.Items=next;}
        if(fields.Count==0)return Results.Ok(ToDetail(quote)); Touch(quote,Actor(context)); Audit(db,quote,quote.UpdatedByUserId,"QUOTE_UPDATED",string.Join(',',fields)); try { await db.SaveChangesAsync(); return Results.Ok(ToDetail(quote)); } catch(DbUpdateConcurrencyException){return Stale();}
    }
    private static async Task<IResult> SendForApprovalAsync(Guid id, SendQuoteForApprovalRequest request, HttpContext context, IAntiforgery antiforgery, ApplicationDbContext db)
    { if(!await Csrf(context,antiforgery))return CsrfFailure(); var quote=await db.Quotes.Include(x=>x.Items).SingleOrDefaultAsync(x=>x.Id==id); if(quote is null)return Results.NotFound(); if(quote.Version!=request.ExpectedVersion)return Stale(); if(quote.Status!=QuoteStatus.Draft)return StateConflict(); var errors=await ApprovalErrorsAsync(quote,db); if(!string.IsNullOrWhiteSpace(request.ApprovalRecipientEmail) && !System.Net.Mail.MailAddress.TryCreate(request.ApprovalRecipientEmail, out _))errors["approvalRecipientEmail"]=["Informe um e-mail de destinatário válido."]; if(request.ValidUntil.HasValue&&request.ValidUntil<=DateTimeOffset.UtcNow)errors["validUntil"]=["Informe uma validade futura."]; if(errors.Count>0)return Results.ValidationProblem(errors); quote.Status=QuoteStatus.AwaitingApproval; quote.SentForApprovalAt=DateTimeOffset.UtcNow; quote.ApprovalRecipientName=Trim(request.ApprovalRecipientName,120); quote.ApprovalRecipientEmail=Trim(request.ApprovalRecipientEmail,254); quote.ValidUntil=request.ValidUntil; Touch(quote,Actor(context)); Audit(db,quote,quote.UpdatedByUserId,"QUOTE_SENT_FOR_APPROVAL",null); try{await db.SaveChangesAsync();return Results.Ok(ToDetail(quote));}catch(DbUpdateConcurrencyException){return Stale();} }
    private static async Task<IResult> RegisterClientResponseAsync(Guid id, RegisterClientResponseRequest request, HttpContext context, IAntiforgery antiforgery, ApplicationDbContext db)
    { if(!await Csrf(context,antiforgery))return CsrfFailure(); var quote=await db.Quotes.Include(x=>x.Items).SingleOrDefaultAsync(x=>x.Id==id); if(quote is null)return Results.NotFound(); if(quote.Version!=request.ExpectedVersion)return Stale(); if(quote.Status!=QuoteStatus.AwaitingApproval)return StateConflict(); if(!Enum.IsDefined(request.ResponseType))return Results.ValidationProblem(new Dictionary<string,string[]> { ["responseType"]=["Selecione um retorno válido do cliente."] }); var notes=Trim(request.Notes,2000); if(request.Notes?.Trim().Length>2000)return Results.ValidationProblem(new Dictionary<string,string[]> { ["notes"]=["As observações devem ter no máximo 2.000 caracteres."] }); quote.ClientResponseType=request.ResponseType; quote.ClientResponseNotes=notes; quote.ClientResponseAt=DateTimeOffset.UtcNow; quote.Status=request.ResponseType switch { QuoteClientResponseType.Approved=>QuoteStatus.Approved, QuoteClientResponseType.ChangesRequested=>QuoteStatus.ChangesRequested, _=>QuoteStatus.Rejected }; Touch(quote,Actor(context)); Audit(db,quote,quote.UpdatedByUserId,request.ResponseType switch { QuoteClientResponseType.Approved=>"QUOTE_APPROVED", QuoteClientResponseType.ChangesRequested=>"QUOTE_CHANGES_REQUESTED", _=>"QUOTE_REJECTED" },notes); try { await db.SaveChangesAsync(); return Results.Ok(ToDetail(quote)); } catch(DbUpdateConcurrencyException) { return Stale(); } }
    private static async Task<IResult> ReopenAsync(Guid id, QuoteVersionRequest request, HttpContext context, IAntiforgery antiforgery, ApplicationDbContext db) => await TransitionAsync(id,request,[QuoteStatus.AwaitingApproval,QuoteStatus.ChangesRequested,QuoteStatus.Rejected,QuoteStatus.Expired],QuoteStatus.Draft,"QUOTE_REOPENED",context,antiforgery,db);
    private static async Task<IResult> CancelAsync(Guid id, QuoteVersionRequest request, HttpContext context, IAntiforgery antiforgery, ApplicationDbContext db) => await TransitionAsync(id,request,[QuoteStatus.Draft,QuoteStatus.AwaitingApproval,QuoteStatus.ChangesRequested],QuoteStatus.Cancelled,"QUOTE_CANCELLED",context,antiforgery,db);
    private static async Task<IResult> TransitionAsync(Guid id, QuoteVersionRequest request, QuoteStatus[] from, QuoteStatus to, string action, HttpContext context, IAntiforgery antiforgery, ApplicationDbContext db)
    { if(!await Csrf(context,antiforgery))return CsrfFailure(); var quote=await db.Quotes.Include(x=>x.Items).SingleOrDefaultAsync(x=>x.Id==id);if(quote is null)return Results.NotFound();if(quote.Version!=request.ExpectedVersion)return Stale();if(!from.Contains(quote.Status))return StateConflict();quote.Status=to;Touch(quote,Actor(context));Audit(db,quote,quote.UpdatedByUserId,action,null);try{await db.SaveChangesAsync();return Results.Ok(ToDetail(quote));}catch(DbUpdateConcurrencyException){return Stale();} }
    private static async Task<IResult> CreateVisitAsync(Guid id, CreateQuoteVisitRequest request, HttpContext context, IAntiforgery antiforgery, ApplicationDbContext db)
    {
        if(!await Csrf(context,antiforgery)) return CsrfFailure(); var quote=await db.Quotes.Include(x=>x.Visits).SingleOrDefaultAsync(x=>x.Id==id); if(quote is null)return Results.NotFound(); if(quote.Visits.Any(v=>v.Status==QuoteVisitStatus.Scheduled))return Results.Conflict(new { error="JÃ¡ existe uma visita agendada para este orÃ§amento." });
        var professional=request.AssignedUserId??quote.ResponsibleUserId; if(!await EligibleProfessionalQuery.ContainsAsync(db, professional))return Results.ValidationProblem(new Dictionary<string,string[]> { ["assignedUserId"]=["Selecione o profissional responsÃ¡vel pela visita."] }); if(request.ScheduledStart==default)return Results.ValidationProblem(new Dictionary<string,string[]> { ["scheduledStart"]=["Informe a data da visita."] }); if(request.ScheduledEnd<=request.ScheduledStart)return Results.ValidationProblem(new Dictionary<string,string[]> { ["scheduledEnd"]=["O horÃ¡rio final deve ser posterior ao horÃ¡rio inicial."] });
        var location=await ServiceAddressAsync(db,quote.CustomerId,request.CustomerUnitId??quote.ServiceUnitId); if(string.IsNullOrWhiteSpace(location))return Results.ValidationProblem(new Dictionary<string,string[]> { ["customerUnitId"]=["Selecione uma unidade ativa do cliente."] }); var actor=Actor(context); var now=DateTimeOffset.UtcNow; var visit=new QuoteVisit { Id=Guid.NewGuid(), QuoteId=id, AssignedUserId=professional!, ScheduledStart=request.ScheduledStart, ScheduledEnd=request.ScheduledEnd, CustomerUnitId=request.CustomerUnitId??quote.ServiceUnitId, LocationSnapshot=location, Notes=Trim(request.Notes,2000), CreatedAtUtc=now, UpdatedAtUtc=now, CreatedByUserId=actor, UpdatedByUserId=actor }; db.QuoteVisits.Add(visit); Touch(quote,actor); Audit(db,quote,actor,"VISIT_SCHEDULED",$"{visit.ScheduledStart:O}|{visit.ScheduledEnd:O}"); await db.SaveChangesAsync(); return Results.Ok(await DetailWithRelations(id,db));
    }
    private static async Task<IResult> RescheduleVisitAsync(Guid id, Guid visitId, RescheduleQuoteVisitRequest request, HttpContext context, IAntiforgery antiforgery, ApplicationDbContext db)
    { if(!await Csrf(context,antiforgery))return CsrfFailure(); var quote=await db.Quotes.SingleOrDefaultAsync(x=>x.Id==id); var visit=await db.QuoteVisits.SingleOrDefaultAsync(x=>x.Id==visitId&&x.QuoteId==id); if(quote is null||visit is null)return Results.NotFound(); if(visit.Status!=QuoteVisitStatus.Scheduled)return Results.Conflict(new { error="Esta visita nÃ£o pode ser reagendada." }); if(request.ScheduledStart==default||request.ScheduledEnd<=request.ScheduledStart)return Results.ValidationProblem(new Dictionary<string,string[]> { ["scheduledEnd"]=["O horÃ¡rio final deve ser posterior ao horÃ¡rio inicial."] }); var old=$"{visit.ScheduledStart:O}|{visit.ScheduledEnd:O}"; visit.ScheduledStart=request.ScheduledStart;visit.ScheduledEnd=request.ScheduledEnd;visit.Notes=Trim(request.Notes,2000)??visit.Notes;visit.UpdatedAtUtc=DateTimeOffset.UtcNow;visit.UpdatedByUserId=Actor(context);Touch(quote,visit.UpdatedByUserId);Audit(db,quote,visit.UpdatedByUserId,"VISIT_RESCHEDULED",$"{old} -> {visit.ScheduledStart:O}|{visit.ScheduledEnd:O}");await db.SaveChangesAsync();return Results.Ok(await DetailWithRelations(id,db)); }
    private static async Task<IResult> ChangeVisitStatusAsync(Guid id, Guid visitId, QuoteVisitStatus status, string action, HttpContext context, IAntiforgery antiforgery, ApplicationDbContext db)
    { if(!await Csrf(context,antiforgery))return CsrfFailure();var quote=await db.Quotes.SingleOrDefaultAsync(x=>x.Id==id);var visit=await db.QuoteVisits.SingleOrDefaultAsync(x=>x.Id==visitId&&x.QuoteId==id);if(quote is null||visit is null)return Results.NotFound();if(visit.Status!=QuoteVisitStatus.Scheduled)return Results.Conflict(new { error="Esta visita nÃ£o pode mais ser alterada." });var actor=Actor(context);visit.Status=status;visit.UpdatedAtUtc=DateTimeOffset.UtcNow;visit.UpdatedByUserId=actor;Touch(quote,actor);Audit(db,quote,actor,action,null);await db.SaveChangesAsync();return Results.Ok(await DetailWithRelations(id,db)); }
    private static async Task<QuoteDetailResponse> DetailWithRelations(Guid id, ApplicationDbContext db) => ToDetail(await db.Quotes.AsNoTracking().Include(x=>x.Items).Include(x=>x.ResponsibleUser).Include(x=>x.Visits).ThenInclude(x=>x.AssignedUser).SingleAsync(x=>x.Id==id));
    private static async Task<IResult?> SubmissionErrorAsync(Quote quote, ApplicationDbContext db){var e=new Dictionary<string,string[]>();if(quote.Items.Count==0)e["items"]=["Inclua pelo menos um serviço."];if(quote.TotalAmount is null)e["totalAmount"]=["Informe o valor total."];if(quote.PaymentType is null)e["paymentType"]=["Informe a condição de pagamento."];if(quote.PaymentType==QuotePaymentType.Installments&&(quote.InstallmentCount is null||quote.InstallmentCount<1))e["installmentCount"]=["Informe uma quantidade válida de parcelas."];if(!await db.Customers.AnyAsync(x=>x.Id==quote.CustomerId&&x.IsActive))e["customerId"]=["O cliente vinculado precisa estar ativo para envio."];return e.Count==0?null:Results.ValidationProblem(e);}
    private static async Task<Dictionary<string, string[]>> ApprovalErrorsAsync(Quote quote, ApplicationDbContext db)
    {
        var errors=new Dictionary<string,string[]>();
        if(quote.Items.Count==0)errors["items"]=["Inclua pelo menos um servi\u00e7o."];
        if(quote.TotalAmount is null)errors["totalAmount"]=["Informe o valor total."];
        if(quote.PaymentType is null)errors["paymentType"]=["Informe a condi\u00e7\u00e3o de pagamento."];
        if(quote.EmployeeCount is null)errors["employeeCount"]=["Informe a quantidade de funcion\u00e1rios."];
        else if(quote.EmployeeCount is < 1 or > 1000000)errors["employeeCount"]=["Informe uma quantidade de funcion\u00e1rios v\u00e1lida."];
        if(quote.RiskDegree is null)errors["riskDegree"]=["Informe o grau de risco."];
        if(string.IsNullOrWhiteSpace(quote.ServiceAddressSnapshot))errors["serviceUnitId"]=["Informe o endere\u00e7o do servi\u00e7o."];
        var customer=await db.Customers.Include(x=>x.Contacts).Include(x=>x.Units).SingleOrDefaultAsync(x=>x.Id==quote.CustomerId);
        if(customer is null||!customer.IsActive)errors["customerId"]=["O cliente vinculado precisa estar ativo para envio."];
        else { if(!customer.Contacts.Any(x=>x.IsActive))errors["contact"]=["Informe um contato ativo para o cliente."]; if(!customer.Units.Any(x=>x.IsActive))errors["unit"]=["Informe uma unidade ativa para o cliente."]; }
        return errors;
    }
    private static IResult? SubmissionCommercialError(Quote quote)
    {
        var errors=new Dictionary<string,string[]>();
        if(quote.EmployeeCount is null)errors["employeeCount"]=["Informe a quantidade de funcion\u00e1rios."];
        else if(quote.EmployeeCount is < 1 or > 1000000)errors["employeeCount"]=["Informe uma quantidade de funcion\u00e1rios v\u00e1lida."];
        if(quote.RiskDegree is null)errors["riskDegree"]=["Informe o grau de risco."];
        else if(!Enum.IsDefined(quote.RiskDegree.Value))errors["riskDegree"]=["Informe um grau de risco v\u00e1lido."];
        if(string.IsNullOrWhiteSpace(quote.ServiceAddressSnapshot))errors["serviceUnitId"]=["Informe o endere\u00e7o do servi\u00e7o."];
        return errors.Count==0?null:Results.ValidationProblem(errors);
    }
    private static async Task<List<Service>?> ActiveServicesAsync(ApplicationDbContext db,IReadOnlyList<QuoteItemRequest> items){var ids=items.Select(x=>x.ServiceId).ToList();if(ids.Distinct().Count()!=ids.Count)return null;var services=await db.Services.Where(x=>ids.Contains(x.Id)&&x.IsActive).ToListAsync();return services.Count==ids.Count?services:null;}
    private static QuoteInput Validate(Guid customerId,IReadOnlyList<QuoteItemRequest>? items,decimal? total,QuotePaymentType? payment,int? count,string? notes,int? employeeCount,QuoteRiskDegree? riskDegree)
    {
        var input=Validate(customerId,items,total,payment,count,notes);
        if(employeeCount is < 1 or > 1000000)return input with { Errors=new Dictionary<string,string[]> { ["employeeCount"]=["Informe uma quantidade de funcion\u00e1rios v\u00e1lida."] } };
        if(riskDegree.HasValue&&!Enum.IsDefined(riskDegree.Value))return input with { Errors=new Dictionary<string,string[]> { ["riskDegree"]=["Informe um grau de risco v\u00e1lido."] } };
        return input;
    }
    private static QuoteInput Validate(Guid customerId,IReadOnlyList<QuoteItemRequest>? items,decimal? total,QuotePaymentType? payment,int? count,string? notes){var e=new Dictionary<string,string[]>();items??=[];notes=string.IsNullOrWhiteSpace(notes)?null:notes.Trim();if(customerId==Guid.Empty)e["customerId"]=["Selecione um cliente."];if(items.Any(x=>x.ServiceId==Guid.Empty))e["items"]=["Selecione serviços válidos."];if(total<0||(total.HasValue&&decimal.Round(total.Value,2)!=total))e["totalAmount"]=["Informe um valor total não negativo com no máximo duas casas decimais."];if(payment==QuotePaymentType.Cash&&count is not null)e["installmentCount"]=["Pagamento à vista não possui parcelas."];if(payment==QuotePaymentType.Installments&&(count is null||count<1||count>999))e["installmentCount"]=["Informe uma quantidade válida de parcelas."];if(notes?.Length>2000)e["notes"]=["As observações devem ter no máximo 2.000 caracteres."];return new QuoteInput(items,total,payment,count,notes,e.Count==0?null:e);}
    private static async Task<string?> ServiceAddressAsync(ApplicationDbContext db,Guid customerId,Guid? unitId){if(!unitId.HasValue)return null;var unit=await db.CustomerUnits.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==unitId.Value&&x.CustomerId==customerId&&x.IsActive);return unit is null?null:FormatAddress(unit);}
    private static string FormatAddress(CustomerUnit unit)=>string.Join(", ",new[]{unit.Name,unit.Street,unit.Number,unit.Complement,unit.District,$"{unit.City}/{unit.StateCode}",unit.PostalCode is null?null:$"CEP {unit.PostalCode}"}.Where(x=>!string.IsNullOrWhiteSpace(x)));
    private static async Task<string?> AllocateNumberAsync(ApplicationDbContext db,int year){if(db.Database.ProviderName?.Contains("Npgsql")!=true){var last=await db.QuoteNumberCounters.SingleOrDefaultAsync(x=>x.Year==year);if(last is null){last=new QuoteNumberCounter{Year=year,LastNumber=1};db.QuoteNumberCounters.Add(last);}else if(last.LastNumber<999999)last.LastNumber++;else return null;return $"ORC-{year}-{last.LastNumber:000000}";} var connection=db.Database.GetDbConnection();if(connection.State!=ConnectionState.Open)await connection.OpenAsync();await using var command=connection.CreateCommand();command.Transaction=db.Database.CurrentTransaction?.GetDbTransaction();command.CommandText="INSERT INTO \"QuoteNumberCounters\" (\"Year\", \"LastNumber\") VALUES (@year, 1) ON CONFLICT (\"Year\") DO UPDATE SET \"LastNumber\" = \"QuoteNumberCounters\".\"LastNumber\" + 1 WHERE \"QuoteNumberCounters\".\"LastNumber\" < 999999 RETURNING \"LastNumber\";";var parameter=command.CreateParameter();parameter.ParameterName="year";parameter.Value=year;command.Parameters.Add(parameter);var value=await command.ExecuteScalarAsync();return value is null ? null : $"ORC-{year}-{Convert.ToInt32(value):000000}";}
    private static string? Trim(string? value,int max) => string.IsNullOrWhiteSpace(value)?null:value.Trim().Length<=max?value.Trim():value.Trim()[..max];
    private static void Touch(Quote q,string actor){q.UpdatedAtUtc=DateTimeOffset.UtcNow;q.UpdatedByUserId=actor;q.Version=Guid.NewGuid();} private static void Audit(ApplicationDbContext d,Quote q,string actor,string action,string? fields)=>d.QuoteAuditRecords.Add(new QuoteAuditRecord{Id=Guid.NewGuid(),QuoteId=q.Id,ActorUserId=actor,Action=action,OccurredAtUtc=DateTimeOffset.UtcNow,ChangedFields=fields}); private static string Actor(HttpContext c)=>c.User.FindFirstValue(ClaimTypes.NameIdentifier)??throw new UnauthorizedAccessException(); private static async Task<bool> Csrf(HttpContext c,IAntiforgery a){try{await a.ValidateRequestAsync(c);return true;}catch(AntiforgeryValidationException){return false;}} private static IResult CsrfFailure()=>Results.BadRequest(new{error="Não foi possível validar a solicitação. Atualize a página e tente novamente."}); private static IResult Stale()=>Results.Conflict(new{error=StaleMessage}); private static IResult StateConflict()=>Results.Conflict(new{error="Esta ação não é permitida para o status atual do orçamento."});
    private static QuoteVisitResponse? CurrentVisit(Quote x) { var visit=x.Visits.Where(v=>v.Status==QuoteVisitStatus.Scheduled).OrderBy(v=>v.ScheduledStart).FirstOrDefault()??x.Visits.OrderByDescending(v=>v.UpdatedAtUtc).FirstOrDefault(); return visit is null?null:new QuoteVisitResponse(visit.Id,visit.AssignedUserId,visit.AssignedUser?.FullName??"",visit.AssignedUser?.Email??"",visit.ScheduledStart,visit.ScheduledEnd,visit.Status,visit.CustomerUnitId,visit.LocationSnapshot,visit.Notes); }
    private static QuoteSummaryResponse ToSummary(Quote x)=>new(x.Id,x.Number,x.CustomerId,x.CustomerLegalNameSnapshot,x.CustomerCnpjSnapshot,x.Status,x.TotalAmount,x.PaymentType,x.InstallmentCount,x.CreatedAtUtc,x.UpdatedAtUtc,x.EmployeeCount,x.RiskDegree,x.ServiceUnitId,x.ServiceAddressSnapshot,x.SentForApprovalAt,x.ValidUntil,x.ResponsibleUserId,x.ResponsibleUser?.FullName,CurrentVisit(x)); private static QuoteDetailResponse ToDetail(Quote x)=>new(x.Id,x.Number,x.CustomerId,x.CustomerLegalNameSnapshot,x.CustomerCnpjSnapshot,x.Status,x.TotalAmount,x.PaymentType,x.InstallmentCount,x.Notes,x.CreatedAtUtc,x.UpdatedAtUtc,x.CreatedByUserId,x.UpdatedByUserId,x.Version,x.Items.OrderBy(i=>i.DisplayOrder).Select(i=>new QuoteItemResponse(i.Id,i.ServiceId,i.ServiceCodeSnapshot,i.ServiceNameSnapshot,i.DisplayOrder)).ToList(),x.EmployeeCount,x.RiskDegree,x.ServiceUnitId,x.ServiceAddressSnapshot,x.SentForApprovalAt,x.ApprovalRecipientName,x.ApprovalRecipientEmail,x.ValidUntil,x.ClientResponseAt,x.ClientResponseType,x.ClientResponseNotes,x.ResponsibleUserId,x.ResponsibleUser?.FullName,x.ResponsibleUser?.Email,CurrentVisit(x)); private sealed record QuoteInput(IReadOnlyList<QuoteItemRequest>? Items,decimal? TotalAmount,QuotePaymentType? PaymentType,int? InstallmentCount,string? Notes,Dictionary<string,string[]>? Errors);
}
